#' Print summary of subjects by race
#'
#' @param race_df Data frame generated by race extraction function
#' @param format Variable indicating if df is dummied or undummied
#' @return summary table of subjects by race
#' @export
format_race <- function(race_df, format) {
    options <- c("undummied", "dummied")
    if (!(format %in% options)) {
        print("The 'format argument should be one of the following options:")
        print("[1] 'dummied'")
        print("[2] 'undummied'")
        print("See ?format_race for more information about these options.")
        return(NULL)
    }
    if (format == "undummied") {
        race_table <- dplyr::count(race_df, race_df$"race")
    }
    if (format == "dummied") {
        race_table <- colSums(race_df |> dplyr::select(-"subjectkey"))
    }
    return(race_table) # TO-DO
}
